/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Geist', 'system-ui', 'sans-serif'],
        mono: ['Geist Mono', 'monospace'],
      },
      colors: {
        'bg-base': '#080808',
        'bg-surface': '#0f0f0f',
        'bg-card': '#141414',
        'bg-elevated': '#1a1a1a',
        'bg-overlay': '#1f1f1f',
        'border-subtle': '#1f1f1f',
        'border-default': '#2a2a2a',
        'border-strong': '#3a3a3a',
        'text-primary': '#f5f5f5',
        'text-secondary': '#a1a1a1',
        'text-tertiary': '#6b6b6b',
        'text-disabled': '#404040',
        brand: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
        },
        'success': '#22c55e',
        'success-muted': '#052e16',
        'warning': '#f59e0b',
        'warning-muted': '#1c1003',
        'error': '#ef4444',
        'error-muted': '#1c0303',
        'info': '#6366f1',
      },
      boxShadow: {
        'card': '0 1px 3px rgba(0,0,0,0.4), 0 1px 2px rgba(0,0,0,0.6)',
        'elevated': '0 4px 12px rgba(0,0,0,0.5)',
        'glow': '0 0 20px rgba(99,102,241,0.15)',
        'modal': '0 20px 60px rgba(0,0,0,0.8)',
      },
      borderRadius: {
        'xs': '4px',
        'sm': '6px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        '2xl': '20px',
        'button': '10px',
        'card': '16px',
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.3s ease-out forwards',
        'fade-in': 'fadeIn 0.2s ease-out forwards',
        'slide-in-up': 'slideInUp 0.2s ease-out forwards',
        'pulse-glow': 'pulseGlow 2s ease-in-out infinite',
        'shimmer': 'shimmer 2s infinite linear',
        'spin-slow': 'spin 3s linear infinite',
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideInUp: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 8px rgba(99,102,241,0.2)' },
          '50%': { boxShadow: '0 0 24px rgba(99,102,241,0.4)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
    },
  },
  plugins: [],
}
